#!/bin/bash
cd ${0%/*}/.. || exit 70
: ${with_siblings:=$(realpath ${0%/*}/../..)}
: ${with_nearby:=${with_siblings?}}
: ${with_submodules:=no}
: ${with_hypogeal_twilight:=${with_nearby?}/hypogeal-twilight}
: ${with_module_nonstd:=${with_nearby?}/module-nonstd}
: ${with_module_posix:=${with_nearby?}/module-posix}
: ${with_module_rigging:=${with_nearby?}/module-rigging}
: ${with_module_rigging_unit:=${with_module_rigging?}}
: ${with_module_unit_rigging:=${with_module_rigging?}}
: ${with_module_sys:=${with_nearby?}/module-sys}
eval \
    ${with_hypogeal_twilight:+with_hypogeal_twilight=$with_hypogeal_twilight} \
    ./buildconf &&
./configure \
    ${deprecated} --without-vernacular-doggerel \
    ${with_nearby:+--with-nearby=$with_nearby} \
    ${with_siblings:+--with-siblings=$with_siblings} \
    ${with_submodules:+--with-submodules=$with_submodules} \
    ${with_hypogeal_twilight:+--with-hypogeal-twilight=$with_hypogeal_twilight} \
    ${with_module_nonstd:+--with-module-nonstd=$with_module_nonstd} \
    ${with_module_posix:+--with-module-posix=$with_module_posix} \
    ${with_module_rigging:+--with-module-rigging=$with_module_rigging} \
    ${deprecated} ${with_module_rigging_unit:+--with-module-rigging-unit=$with_module_rigging_unit} \
    ${deprecated} ${with_module_unit_rigging:+--with-module-unit-rigging=$with_module_unit_rigging} \
    ${with_module_sys:+--with-module-sys=$with_module_sys} \
    ${end} &&
make &&
make check &&
echo OK DONE
