#!/bin/bash
cd ${0%/*}/.. || exit 70
: ${with_siblings:=$(realpath ${0%/*}/..)}
: ${with_nearby:=$(realpath ${0%/*}/../..)}
: ${with_hypogeal_twilight:=${with_nearby?}/hypogeal-twilight}
: ${with_module_std:=${with_nearby?}/module-std}
: ${with_module_rigging:=${with_nearby?}/module-rigging}
: ${enable_configure_debug:=no}
: ${enable_configure_verbose:=no}
eval \
    ${with_hypogeal_twilight:+with_hypogeal_twilight=$with_hypogeal_twilight} \
    ./buildconf &&
./configure \
    ${enable_configure_debug:+--enable-configure-debug=$enable_configure_debug} \
    ${enable_configure_verbose:+--enable-configure-verbose=$enable_configure_verbose} \
    --without-siblings \
    --without-vernacular-doggerel \
    ${with_nearby:+--with-nearby=$with_nearby} \
    ${with_hypogeal_twilight:+--with-hypogeal-twilight=$with_hypogeal_twilight} \
    ${with_module_rigging:+--with-module-rigging=$with_module_rigging} \
    ${with_module_std:+--with-module-std=$with_module_std} \
    --with-std-scold=/opt/scold \
    ${end} && 
make &&
make check &&
echo OK DONE
