#!/bin/bash
# For terms and provenance see the LICENSE file at the top of this repository.
cd ${0%/*}/.. || exit 70
: ${with_nearby:=$(realpath ${0%/*}/../..)}
: ${with_hypogeal_twilight:=${with_nearby?}/hypogeal-twilight}
: ${with_module_nonstd:=${with_nearby?}/module-nonstd}
: ${with_module_posix:=${with_nearby?}/module-posix}
: ${with_module_rigging:=${with_nearby?}/module-rigging}
: ${with_module_sys:=${with_nearby?}/module-sys}
eval \
  ${with_hypogeal_twilight:+with_hypogeal_twilight=$with_hypogeal_twilight} \
  ./buildconf &&
./configure \
    ${with_nearby:+--with-nearby=$with_nearby} \
    ${with_hypogeal_twilight:+--with-hypogeal-twilight=$with_hypogeal_twilight} \
    ${with_module_nonstd:+--with-module-nonstd=$with_module_nonstd} \
    ${with_module_rigging:+--with-module-rigging=$with_module_rigging} \
    ${with_module_posix:+--with-module-posix=$with_module_posix} \
    ${with_module_sys:+--with-module-sys=$with_module_sys} \
    --without-vernacular-doggerel \
    --without-submodules \
    ${end} &&
make &&
make check &&
echo OK DONE
