#!/bin/bash
# For terms and provenance see the LICENSE file at the top of this repository.
cd ${0%/*}/.. || exit 70
: ${with_siblings:=$(realpath ${0%/*}/..)}
: ${with_nearby:=$(realpath ${0%/*}/../..)}
: ${with_nonstd_gcc:=/exp/gcc/9}
: ${with_hypogeal_twilight:=${with_nearby?}/hypogeal-twilight}
: ${with_module_half:=${with_nearby?}/module-half}
: ${with_module_nonstd:=${with_nearby?}/module-nonstd}
: ${with_module_posix:=${with_nearby?}/module-posix}
: ${with_module_rigging:=${with_nearby?}/module-rigging}
: ${with_module_slurp:=${with_nearby?}/module-slurp}
: ${with_module_std:=${with_nearby?}/module-std}
: ${with_module_sys:=${with_nearby?}/module-sys}
: ${with_nonstd_half:=/opt/nonstd/half}
: ${enable_configure_debug:=no}
: ${enable_configure_verbose:=no}
eval \
    ${with_hypogeal_twilight:+with_hypogeal_twilight=$with_hypogeal_twilight} \
    ./buildconf &&
./configure \
    ${enable_configure_debug:+--enable-configure-debug=$enable_configure_debug} \
    ${enable_configure_verbose:+--enable-configure-verbose=$enable_configure_verbose} \
    --without-siblings \
    ${with_nearby:+--with-nearby=$with_nearby} \
    ${with_nonstd_gcc:+--with-nonstd-gcc=$with_nonstd_gcc} \
    ${with_hypogeal_twilight:+--with-hypogeal-twilight=$with_hypogeal_twilight} \
    ${with_module_half:+--with-module-half=$with_module_half} \
    ${with_module_nonstd:+--with-module-nonstd=$with_module_nonstd} \
    ${with_module_posix:+--with-module-posix=$with_module_posix} \
    ${with_module_rigging:+--with-module-rigging=$with_module_rigging} \
    ${with_module_slurp:+--with-module-slurp=$with_module_slurp} \
    ${with_module_std:+--with-module-std=$with_module_std} \
    ${with_module_sys:+--with-module-sys=$with_module_sys} \
    ${with_nonstd_half:+--with-nonstd-half=$with_nonstd_half} \
    --with-std-scold=/opt/scold \
    ${end} && 
make &&
make check &&
echo OK DONE
