#!/bin/bash
cd ${0%/*}/.. || exit 70
: ${with_nearby:=$(realpath ${0%/*}/../..)}
: ${with_hypogeal_twilight:=${with_nearby?}/hypogeal-twilight}
: ${with_module_rigging:=${with_nearby?}/module-rigging}
eval \
  ${with_hypogeal_twilight:+with_hypogeal_twilight=$with_hypogeal_twilight} \
  ./buildconf &&
./configure \
    ${with_nearby:+--with-nearby=$with_nearby} \
    ${with_hypogeal_twilight:+--with-hypogeal-twilight=$with_hypogeal_twilight} \
    ${with_module_rigging:+--with-module-rigging=$with_module_rigging} \
    --without-vernacular-doggerel \
    --without-submodules \
    ${end} &&
make &&
make check &&
echo OK DONE
