#!/bin/bash
#
# the full end-to-end build
#
#   buildconf
#   configure
#   make [all]
#   make check
#
# Usage:
#
#   ./maintenance/e2e     (no options)
#
#   prefix=/usr/local \
#   with_std_tunitas=/opt/tunitas \
#   with_temerarious_flagship=/opt/tunitas \
#   ./maintenance/e2e
# 
# to build without submodules
#
#  with_submodules=no ./maintenance/e2e       (this works because --with-THING=no is --without-THING)
#
# The scold module "with" variables will naturally default to /opt/scold
# The tunitas "with" variables would be expected to be in /opt/tunitas
#
cd ${0%/*}/.. || exit 70
: ${prefix:=/exp/tunitas}
: ${with_std_tunitas:=/opt/tunitas}
: ${with_std_scold:=${with_std_tunitas%/*}/scold}
: ${with_siblings:=${PWD%/*}}
: ${with_temerarious_flagship:=${with_siblings?}/temerarious-flagship}
if [[ -d ${PWD%/*}/nearby ]] ; then
    : ${with_nearby:=${PWD%/*}/nearby}
    : ${with_module_rigging:=${with_nearby?}/module-rigging}
else
    : ${with_nearby:=no}
    : ${with_module_rigging:=no}
fi
: ${with_submodules:=no} # nope ..... : ${with_submodules:=${PWD}/submodules} # must be a full path
declare __subnearby
if [[ no == ${with_submodules:-no} ]] ; then
    # could be no
    __subnearby=${with_nearby?}
elif [[ yes == ${__subnearby:-no} ]] ; then
    echo "${0##*/}: error, submodules cannot be merely 'yes'" 1>&2
    exit 78
else
    # [[unchecked]] musn't be merely 'yes' or a non-existent directory 
    __subnearby=${with_submodules?}
fi
if [[ no == ${__subnearby:-no} ]] ; then
    : ${with_hypogeal_twilight:=$with_std_scold}
    : ${with_module_options:=no}
    : ${with_module_std:=no}
elif [[ yes == ${__subnearby:-no} ]] ; then
    echo "${0##*/}: error, submodules or nearby cannot be merely 'yes'" 1>&2
    exit 78
else
    : ${with_hypogeal_twilight:=${__subnearby?}/hypogeal-twilight}
    : ${with_module_options:=${__subnearby?}/module-options}
    : ${with_module_std:=${__subnearby?}/module-std}
fi
: ${with_module_httpserver:=no}
# required: at least nonstd-libhttpserver-0.9.0-8.1.ipv6+poll+regex
: ${with_nonstd_libhttpserver:=/opt/nonstd/libhttpserver}
: ${with_module_nonstd:=no}
: ${with_module_posix:=no}
: ${with_module_string:=no}
eval \
    ${prefix:+prefix=$prefix} \
    ${with_hypogeal_twilight:+with_hypogeal_twilight=$with_hypogeal_twilight} \
    ${with_temerarious_flagship:+with_temerarious_flagship=$with_temerarious_flagship} \
    ./buildconf &&
./configure \
    --enable-configure-verbose \
    --disable-mock-build \
    ${prefix:+--prefix=$prefix} \
    ${with_nearby:+--with-nearby=$with_nearby} ${with_external:+--with-external=$with_external} \
    ${with_submodules:+--with-submodules=$with_submodules} \
    ${with_hypogeal_twilight:+--with-hypogeal-twilight=$with_hypogeal_twilight} \
    ${with_temerarious_flagship:+--with-temerarious-flagship=$with_temerarious_flagship} \
    ${with_module_c:+--with-module-c=$with_module_c} \
    ${with_module_httpserver:+--with-module-httpserver=$with_module_httpserver} \
    ${with_nonstd_libhttpserver:+--with-nonstd-libhttpserver=$with_nonstd_libhttpserver} \
    ${with_module_nonstd:+--with-module-nonstd=$with_module_nonstd} \
    ${with_module_options:+--with-module-options=$with_module_options} \
    ${with_module_posix:+--with-module-posix=$with_module_posix} \
    ${with_module_rigging:+--with-module-rigging=$with_module_rigging} \
    ${with_module_std:+--with-module-sys=$with_module_std} \
    ${with_module_string:+--with-module-c-string=$with_module_string} \
    ${with_std_tunitas:+--with-std-tunitas=$with_std_tunitas} \
    ${with_std_scold:+--with-std-scold=$with_std_scold} \
    ${end} &&
make &&
make check &&
echo OK DONE
