#!/bin/bash -p
# Copyright Yahoo Inc, 2021.
# Licensed under the terms of the Apache-2.0 license.
# For terms, see the LICENSE file at https://github.com/yahoo/tunitas-basics/blob/master/LICENSE
# For terms, see the LICENSE file at https://git.tunitas.technology/all/components/basics/tree/LICENSE
#
# This could all now be collapsed into .../maintenance/nearby
source ${with_temerarious_flagship:-${with_worktrees:-/build/worktrees}/temerarious-flagship/v2.${TEMERARIOUS:-${TUNITAS:-${NEARBY:-${TAG?}}}}}/maintenance/fragment/definitions.sh || exit 72

with_build=${with_build?} \
with_nearby=${with_nearby:-${with_build?}/scold} \
with_hypogeal_twilight=${with_hypogeal_twilight?} \
with_module_langu=${with_module_langu?} \
with_module_nonstd=${with_module_nonstd?} \
with_module_sys=${with_module_sys?} \
\
with_module_cli_core=${with_module_cli_core?} \
with_module_cli=${with_module_cli?} \
with_module_options=${with_module_options?} \
\
with_module_rigging_app=${with_module_rigging_app?} \
with_module_rigging_core=${with_module_rigging_core?} \
with_module_rigging=${with_module_rigging?} \
with_nonstd_cppunit=${with_nonstd_cppunit:-no} \
with_module_cppunit=${with_module_cppunit:-no} \
\
with_module_c=${with_module_c:-no} \
with_module_format=${with_module_format:-no} \
with_module_ip=${with_module_ip:-no} \
with_module_posix=${with_module_posix:-no} \
with_module_slurp=${with_module_slurp:-no} \
with_module_std=${with_module_std:-no} \
with_module_string=${with_module_string:-no} \
\
with_microhttpd__=${with_microhttpd__?} \
with_microhttpd=${with_microhttpd?} \
\
with_temerarious_flagship=${with_temerarious_flagship?} \
\
exec ${0%/*}/nearby
