#!/bin/bash -p
# Copyright Yahoo Inc, 2021.
# Licensed under the terms of the Apache-2.0 license.
# For terms, see the LICENSE file at https://github.com/yahoo/tunitas-basics/blob/master/LICENSE
# For terms, see the LICENSE file at https://git.tunitas.technology/all/components/basics/tree/LICENSE
: ${with_build:=/build}
: ${with_worktrees:=${with_build?}/worktrees}
: ${TAG:=PLUS}

TAG=${TAG?} \
with_build=${with_build?} \
\
exec ${0%/*}/v2
