#!/bin/bash
cd ${0%/*}/.. || exit 70
: ${with_nearby:=$(cd ${0%/*}/../.. ; pwd)}
: ${with_hypogeal_twilight:=${with_nearby?}/hypogeal-twilight}
: ${with_module_nonstd:=${with_nearby?}/module-nonstd}
: ${with_module_rigging:=${with_nearby?}/module-rigging}
eval \
    ${with_hypogeal_twilight:+with_hypogeal_twilight=$with_hypogeal_twilight} \
    ./buildconf &&
./configure \
    --without-submodules \
    --without-vernacular-doggerel \
    ${with_hypogeal_twilight:+--with-hypogeal-twilight=$with_hypogeal_twilight} \
    ${with_module_nonstd:+--with-module-nonstd=$with_module_nonstd} \
    ${with_module_rigging:+--with-module-rigging=$with_module_rigging} \
    ${end} &&
make &&
make check &&
echo OK DONE
